from enum import IntEnum
import logging
import math
import numpy
import time
import usb.core
import yaml
from socket_module import socket_modules


#
# NOTE NOTE NOTE:  in all of what follows, "channel number" means a pin
# driver channel number according to my numbering convention, NOT any of
# the channel numbering conventions shown in the ALLPRO88 technical
# documentation (I've identified at least two).  by my convention channels
# are numbered sequentially from 0 in the order of their control register
# addresses.
#


#
# =============================================================================
#
#                           Register Bit Definitions
#
# =============================================================================
#


class PCR(IntEnum):
	"""
	PCR (power supply control register) configuration bits.
	"""
	# power supplies off, red busy LED off, green idle LED on
	DISABLE = 0x00
	# enables power supplies, and lights red busy LED
	ENABLE = 0x01
	# turns off green idle LED
	NIDLE = 0x02


class PINCON(IntEnum):
	"""
	Pin driver configuration register bits.

	Except for the case of combining the pull-up supply with other
	voltage sources, it's almost certainly an error to activate more
	than one voltage source at the same time, however reverse
	protection diodes prevent any voltage source from damaging other
	voltage sources, so any combination of them can be activated
	simultaneously without doing damage.

	The highest possible output voltage is approximately 25 V, which
	would dissipate less than 1/8 W in the 5.4 kOhm pull-down resistor.
	I don't know what it's rated for, but it is probably safe to enable
	the pull-down resistor in combination with any of the voltage
	sources at any output voltage.

	Only the pull-up voltage source is safe to enable in combination
	with the TTL low drive output, or the current-limited test source
	if set to a sufficiently low current.  Enabling any other voltage
	source in combination with the TTL low output will destroy
	hard-to-replace surface-mount components on the channel's hybrid
	module.

	Enabling the ground drive transistor in combination with any
	voltage source other than the pull-up source or the current-limited
	test srouce will destroy components.

	NOTE:  the resistors in the circuitry of the hybrid modules are
	printed into the module as part of the substrate.  All other
	components are standard off-the-shelf parts, but the resistors
	*cannot* be replaced.  If a single one is damanged due to
	over-current conditions the entire hybrid module will have to be
	replaced.  The only source of replacement hybrid modules is a
	parts-donor unit.
	"""
	DISABLE = 0x00	# disable ("float") pin
	GND = 0x01	# turn on FET pulling pin to ground
	VDAC = 0x02	# turn on DAC output power transistor
	VTST = 0x04	# turn on current- and voltage-limited source driver
	LOGICH = 0x08	# turn on +5 V ("TTL high") driver
	PULLUP = 0x10	# turn on pull-up driver (2.7 kOhm to VPUL source)
	LOGICL = 0x20	# turn on 0 V ("TTL low") driver (50 Ohm to ground)
	POSCLK = 0x40	# clock phase 1 drives TTL high, phase 0 drives TTL low
	NEGCLK = 0x60	# clock phase 0 drives TTL high, phase 1 drives TTL low
	PULLDN = 0x80	# turn on pull-down driver (5.4 kOhm to ground)


class CLKGEN_MODE(IntEnum):
	"""
	TTL clock generator configuration register bits.
	"""
	# from the service manual, the two timer phases are generated by a
	# PAL16R6 chip whose inputs include a clock from a free-running
	# oscillator and 8 bits latched from the data bus by a x273
	# register.  the schematic includes labels on some connections.
	# two of the PAL's outputs are labelled "PHASE0", "PHASE1", and
	# lead off board via a connector to be the two phases driving the
	# pin drivers.  the 6 other outputs are labelled 125KHz, 250KHz,
	# 500KHz, 1MHz, 2MHz, and 4MHz, which are together labelled "PHASE
	# TAPS".  they don't appear to be connected to anything except the
	# 4MHz output which loops back to another PAL one of whose outputs
	# provides the clock for the x273 register.  my guess is something
	# is being done to ensure the clock generator PAL's configuration
	# bits are latched at a special point in its internal state
	# sequence.  the lowest three data bus bits input to the timer PAL
	# are labelled "PHSEL0", "PHSEL1" and "PHSEL2".  there are no
	# labels on the rest.  what it *looks* like to me is the PAL is
	# implementing a ripple counter, dividing down an input clock by
	# factors of 2, with one of the six divided down outputs or
	# "nothing" switched onto an output by the three configuration
	# bits, and the other phase output being generated as the inverse
	# of the first.  that would suggest that 0x00 through 0x07 should
	# be valid configurations (6 frequencies, off, and a manually
	# toggle option, for a total of 8 configurations).  kevtris' notes
	# say 0x07 is not valid, and none of his configurations correspond
	# to the 125kHz output shown on the schematic.  he says not to
	# select 0x07 or it will damage the circuit, but I would have
	# guessed it enables the 125kHz output.  it's possible his PAL chip
	# is malfunctioning, but I've confirmed that my systems behave the
	# same way.  there is no 125 kHz clock configuration.  how could
	# any selection damage something?  the concern here is not in the
	# clock generator circuit but in the pin driver circuits.  a pin
	# driver uses one phase to switch the TTL high output on and off
	# and the other phase to switch the TTL low output on and off, so
	# the two phases must never both be on at the same time or both TTL
	# high and low outputs will be enabled simultaneously and short out
	# whichever pin driver is set to clock output mode.  I believe that
	# if no pin drivers are set to clock mode there is no risk in
	# experimenting with the clock generator configuration bits.
	#
	# the schematic makes no mention of the "polarity" bit 0x80.
	# kevtris must have discovered it by trial and error.

	DISABLE = 0x00		# both phases low.  pin drivers will float
	BITBANG = 0x01		# use POLARITY to select state
	CLK_4MHZ = 0x02
	CLK_2MHZ = 0x03
	CLK_1MHZ = 0x04
	CLK_500KHZ = 0x05
	CLK_250KHZ = 0x06
	CLK_125KHZ = 0x07	# not correctly implemented.  do not use!
	POLARITY = 0x80		# 1 = phase 0 is high in BITBANG mode


#
# =============================================================================
#
#                           Channel Driver Interface
#
# =============================================================================
#


class volt(float):
	"""
	Sub-class of float used to indicate to a DAC proxy that the value
	should be interpreted as a voltage, not a DAC count.
	"""
	pass


class dacregister(object):
	"""
	Write a value to a DAC register.  Provides type conversion and
	range checking to ensure the value written is allowed, and will
	optionally apply a volts-to-DAC count calibration function.
	"""
	def __init__(self, address = None, transient = 0., cal_key = None):
		# fixed register address, if known.  if not known, or None,
		# the .address() method must be overridden.

		self._address = address

		# transient response time in seconds.  for convenience,
		# this code can enforce a pause after changing a DAC, to
		# give the respective voltage time to slew.  this removes
		# the need to include those pauses in calling code
		# everywhere they are required.
		#
		# NOTE:  it is possible, and often convenient, to set
		# various DACs before turning on the power supplies that
		# drive the DACs, so that when power is applied the pins of
		# a part ramp up in voltage together.  obviously when that
		# is done the pause that should be included to allow for
		# voltage slews needs to be inserted when the power
		# supplies are turned on, not when the DAC register is set.
		# with that example in mind, the inclusion of the transient
		# pause feature here does not guarantee that all voltage
		# slew pauses associated with a given DAC are necessarily
		# accounted for.  thought should always be put into where a
		# delay might still be needed.

		self.transient = transient

		# calibration function look-up key.  you might think it
		# would make more sense to simply set the calibration
		# function here directly instead of this nonsense of a key
		# that we use to look up in a dictionary elsewhere.  the
		# problem is that a descriptor (used to implement an
		# attribute of a class) is only a single instance:  there
		# is one instance of the descriptor class for the class
		# definition to which it is attached, there is not a new
		# instance of the descriptor for each instance of the
		# class.  that means that data stored in the descriptor
		# instance is shared across all instances of the class
		# whose attribute it is being used to implement.  we cannot
		# store any data here that we might want to configure
		# differently for different programmers.  therefore we
		# cannot put the calibration curve itself here, only a
		# shared key used to look up the programmer-specific
		# calibration function in a table stored elsewhere.

		self.cal_key = cal_key

	def address(self, obj):
		"""
		This DAC register's address.  obj is the instance of the
		class to which this descriptor is attached:  for pin driver
		VDAC registers obj is the associated channel_proxy
		instance, for all others it's the allpro88 programmer
		instance.
		"""
		# subclasses must override this if they need something
		# other than a single, fixed, address.
		assert self._address is not None
		return self._address

	def cal(self, dac, obj):
		"""
		Convert DAC count to voltage.  If this descriptor was
		initialized with cal_key set to None (the default) then a
		default generic calibration function is used.  Otherwise,
		obj.cal[self.cal_key] is retrieved, and the result of
		passing the DAC value to that function is used as the
		return value.
		"""
		if self.cal_key is None:
			# default calibration
			return dac * 25.5 / 256.
		return obj.cal[self.cal_key](dac)

	def __set__(self, obj, val):
		"""
		Set the DAC register.  If the value is a volt object, the
		calibration function is applied to convert the voltage to
		an integer count, which is then written to the DAC
		register.  Otherwise, the value supplied is converted to an
		integer, and then written to the DAC register.  In both
		cases, before writing the integer DAC count to the register
		it is confirmed to be in [0, 255].  If any of the
		conversion steps or safety checks fail, an exception will
		be raised, typically ValueError, but OverflowError and
		others are possible depending on the nature of the failure.
		"""
		# if the calling code has given us a volt value, convert to
		# DAC count
		if type(val) is volt:
			dac = self.invcal(val, obj)
		else:
			# verify int compatibility
			dac = int(val)
		# verify range
		if not 0 <= dac <= 255:
			raise ValueError("0 <= dac <= 255:  %d" % dac)
		# OK
		obj.write_addr(self.address(obj), dac)
		time.sleep(self.transient)

	def invcal(self, v, obj):
		"""
		Convert voltage to DAC count.  Uses a bisection search to
		invert the .cal() method and returns the integer DAC count
		value that most closely approximates the requested voltage.
		Raises ValueError if the requested voltage is above the
		highest voltage of the DAC.  Voltages that are below the
		limits of the DAC are mapped to the lowest available
		voltage.
		"""
		# most DAC-to-voltage calibration mappings are linear or
		# quadratic polynomials, with a cut-off at the low end
		# below which the voltage is a constant.  rather than
		# constructing a generic inverse of such functions, because
		# the number of possible values is so small, we use a
		# bisection search to invert the calibration by
		# brute-force.  this loop's worst case completes in just 8
		# iterations, and doing it this way has the advantage of
		# always working for any DAC-to-voltage calibration mapping
		# whose slope doesn't change sign.
		lo, hi = 0, 256
		if v >= self.cal(255.5, obj):
			raise ValueError("voltage too high:  requested %g V > DAC limit of %g V" % (v, self.cal(255, obj)))
		while hi - lo > 0.5:
			mid = (hi + lo) / 2
			cal = self.cal(mid, obj)
			if cal == v:
				dac = mid
				break
			elif cal < v:
				lo = mid
			else:	# cal > v:
				hi = mid
		else:
			dac = lo
		# can't use round() because it rounds half odd integers up
		# but half even integers douwn.  round(1.5) == round(2.5).
		# perhaps if we extended the loop until hi-lo <= 0.25 and
		# then used round() it would be, statistically speaking, a
		# better inverse, but *this* algorithm, with the loop above
		# as-is and the rounding below as-is produces the answers I
		# want when tested against actual example calibration
		# curves.
		dac = min(255, math.floor(dac + 0.5))
		assert type(dac) is int and 0 <= dac <= 255
		# some calibration mappings predict a constant output below
		# some threshold.  if we've chosen a DAC setting in such an
		# interval, choose the lowest such DAC setting (typically
		# 0, but check).
		while dac > 0 and self.cal(dac - 1, obj) == self.cal(dac, obj):
			dac -= 1
		return dac


class vdacregister(dacregister):
	# version of dacregister that gets the address dynamically from the
	# object to which it is attached.
	def address(self, obj):
		return obj.address + 3


class channel_proxy(object):
	"""
	An interface to the capabilities of a single pin driver channel.
	Features include setting the configuration of the pin, measuring
	the voltage on a pin, comparing that voltage to a threshold,
	briefly pulsing the pin and enabling and disabling the pin's bypass
	capacitor.
	"""
	def __init__(self, programmer, channel, cal_data = {"min": 0.1892, "poly": (-0.6891, 0.09901, 4.479e-06)}):
		# allpro88 instance with which we are associated
		self.programmer = programmer
		# integer channel number
		if not 0 <= channel <= 87:
			raise ValueError(channel)
		self.channel = channel
		# start address of register group for this channel
		if self.channel <= 0x27:
			self.address = self.channel << 4
		else:
			self.address = (self.channel + 0x18) << 4
		# bypass capacitor control register
		# FIXME:  the bypass capacitor feature including its
		# associated control logic and address decode circuitry
		# lives on the socket module.  it's not part of the
		# programmer.  if a different socket module gets installed
		# who knows what these addresses would control.  this
		# address range is probably meant to be a generic expansion
		# port feature, and it would probably be better being
		# handled by the socket_module class somehow so that the
		# correct code is attached to the electronics.
		if channel <= 0x27:
			self.bypass_address = 0x280 + channel
		elif channel <= 0x2f:
			self.bypass_address = 0x2c0 + (channel - 0x28)
		else:
			# only first 48 channels have bypass capacitors
			self.bypass_address = None
		# set the calibration
		self.set_cal(cal_data)

	config = property(fset = lambda self, config: self.programmer.write_addr(self.address, config))

	vdac = vdacregister(cal_key = "VDAC")

	def write_addr(self, *args, **kwargs):
		# plumbing for the vdac descriptor
		return self.programmer.write_addr(*args, **kwargs)

	def set_cal(self, cal_data):
		poly = numpy.polynomial.Polynomial(cal_data["poly"])
		self.cal = {
			"VDAC": (lambda dac: max(cal_data["min"], poly(dac)))
		}

	def __bool__(self):
		"""
		Boolean state = state of comparator.  Set VTH to threshold
		voltage.

		NOTE:  with VTH and pin driver power supplies off, in
		some units the comparator reports logic 0 while in others
		it reports logic 1.  In the two examples I have access to,
		the behaviour is consistent across all channels:  they
		either all report 0 in this configuration or all report 1,
		which suggests that the behaviour is not due to random
		fluctuations in comparator behaviour, but is a circuit
		design choice that ensures one or the other results, and
		that there was a revision in this feature at some point.
		"""
		return bool(self.programmer.read_addr(self.address) & 1)

	def measure_v(self, n = 1):
		"""
		Use a bisection search with VTH to measure the voltage on
		this channel's pin.  Repeat the measurement n times
		(default = 1) and report the median of the measurements.
		NOTE:  VTH is left set to (an approximation of) the
		measured voltage.
		"""
		n = int(n)
		assert n > 0
		volts = []
		for i in range(n):
			dac, = self.programmer.write_command("M%02X" % self.channel)
			volts.append(self.programmer.vth.cal(dac, self.programmer))
		return numpy.median(volts)

	def pulse(self, microseconds, config, final_config):
		"""
		Switch this channel's configuration to config, hold it for
		the given number of microseconds, then switch the
		configuration to final_config.

		It is common for programmable devices to require a short
		pulse on a single pin to affect the programming operation.
		Usually there are strict requirements for the duration of
		the pulse.  This method is provided to meet the needs of
		such parts.  The pulse is generated by the USB interface's
		firmware, using a precision timing loop.

		ValueError is raised if the requested pulse duration is
		outside the range [0 us, 65535 us].

		NOTE:  the shortest pulse the firmware can generate is
		approximately 5 us.  It is not an error to request a
		shorter pulse, but a 5 us pulse will be generated in those
		cases.
		"""
		microseconds = int(microseconds)
		if microseconds < 0:
			raise ValueError("pulse duration < 0")
		if microseconds > 0xffff:
			# FIXME:  if such a long pulse, longer than ~65 ms,
			# is desired then probably also the duration does
			# not need to be controled with microsecond
			# accuracy.  if the tolerance can be relaxed
			# enough, the pulse could be implemented in
			# software, here, on the host side.
			raise ValueError("pulse duration too long:  %d us" % microseconds)
		self.programmer.write_command("P%02X%04X%02X%02X" % (self.channel, microseconds, config, final_config))

	@property
	def bypass(self):
		"""
		Write-only boolean to set the state of this channels'
		bypass capacitor.  True = enabled.  Not all channels have
		bypass capacitors.  It is not an error to attempt to enable
		or disable the bypass capacitor of a channel that does not
		have one.  The request is silently ignored.  This
		simplifies "reset everything" loops.
		"""
		raise NotImplementedError

	@bypass.setter
	def bypass(self, boolean):
		# bypass capacitor is turned on and off with bit 0.
		# silently ignore requests to turn on or off bypass
		# capacitors on channels that don't have them.
		if self.bypass_address is not None:
			self.programmer.write_addr(self.bypass_address, 1 if boolean else 0)

	@property
	def physical(self):
		"""
		Physical location of this channel within the programmer.
		Value is a tuple:  (pin driver group #, DAC chip identifier
		#, hybrid identifier #, channel # on hybrid).  This assists
		with the interpretation of self test results, e.g., are all
		of the malfunctioning channels on the same pin driver group
		plug-in board, are they on the same hybrid module?
		"""
		return (
			# group # printed on motherboard PCB
			self.channel // 8,
			# DAC chip ident., U# printed on channel driver PCB
			self.channel % 8 + 1,
			# hybrid ident., H# printed on channel driver PCB
			(self.channel % 8) // 2 + 1,
			# hybrid channel number (as numbered by me for my
			# hybrid tester jig)
			(self.channel % 8) % 2
		)


#
# =============================================================================
#
#                           Channel Driver Wrappers
#
# =============================================================================
#


#
# The code here is used in .__init__() methods of classes defining parts to
# create attributes that provide high-level interfaces to pins on the part.
#
# These classes all provide .read() and .write() methods to set and
# retrieve the value of the pins they control.  To reduce the amount of
# typing, and help make code readable, the devices module provides the
# read_write_proxy class to create descriptors that hide the .read() and
# .write() calls.
#


class flag(object):
	"""
	A tri-state logic interface on one of a socket's pins, with default
	initial value.  The pin can be used for output or input.  To set
	the state of the pin, i.e., to use the pin for output, write a
	boolean value.  To use the pin for input, set it to None to float
	the pin.  To read the state of the pin, read a value.

	The pin is initialized to the value set by the keyword argument
	default.

	NOTE:  by default, the pin will be set to output, and initialized
	to the inactive (False) state.  If that requires a voltage to be
	applied to the pin, it will not take effect until power is applied
	to the socket.
	"""
	def __init__(self, socket, pin_number, active, inactive, flt = PINCON.DISABLE, default = False):
		"""
		socket, pin_number = the socket and socket pin number this
		flag is controlling.

		active = the PINCON register configuration for the active
		state.

		inactive = the PINCON register configuration for the
		inactive state.

		flt = the PINCON register configuration for the floating
		state.

		If none of the three states corresponds to a VDAC
		controlled voltage, the VDAC driver will be set to 0.
		"""
		self.socket = socket
		self.pin_number =  pin_number
		self.active = active
		self.inactive = inactive
		self.flt = flt
		self.default = default
		# set initial state
		if PINCON.VDAC not in (active, inactive, flt):
			self.socket[self.pin_number].vdac = 0
		self.channel.bypass = False
		self.write(self.default)

	@property
	def channel(self):
		"""
		The channel_proxy instance for this flag's pin.
		"""
		return self.socket[self.pin_number]

	def read(self):
		"""
		The boolean state of the pin, assessed by comparing the
		voltage on the pin to the VTH voltage.  Above VTH is
		reported as True, below as False, but a subclass might
		override this, for example to implement an active-low flag
		the result would be inverted.
		"""
		return bool(self.channel)

	def bool_to_config(self, boolean):
		"""
		Convert boolean value to the corresponding channel
		configuration register value.  The return value is
		self.active or self.inactive if boolean is (equivalent to)
		True or False, respectively.  If boolean is None then
		self.flt is returned.
		"""
		return self.flt if boolean is None else self.active if boolean else self.inactive

	def write(self, boolean):
		"""
		Set the state of the flag to the state corresponding to
		boolean.  See .bool_to_config() for the mapping from
		boolean value to flag state.
		"""
		self.channel.config = self.bool_to_config(boolean)

	def pulse(self, microseconds, boolean, final_boolean):
		"""
		Set the pin driver channel configuration to the state
		corresponding to boolean, hold it for the given number of
		microseconds, then set it to the state corresponding to
		final_boolean.  See .bool_to_config() for the mapping from
		boolean value to flag state.
		"""
		self.channel.pulse(microseconds, self.bool_to_config(boolean), self.bool_to_config(final_boolean))


class flag_ttl(flag):
	"""
	Boolean pin configured for active high TTL logic levels.
	"""
	def __init__(self, socket, pin_number, **kwargs):
		"""
		kwargs are passed to parent class, e.g., what state to use
		for floating.
		"""
		super(flag_ttl, self).__init__(socket, pin_number, active = PINCON.LOGICH, inactive = PINCON.LOGICL, **kwargs)


class flag_ttl_active_low(flag):
	"""
	Boolean pin configured for active low TTL logic levels.
	"""
	def __init__(self, socket, pin_number, **kwargs):
		"""
		kwargs are passed to parent class, e.g., what state to use
		for floating.
		"""
		super(flag_ttl_active_low, self).__init__(socket, pin_number, active = PINCON.LOGICL, inactive = PINCON.LOGICH, **kwargs)

	def read(self):
		return not super(flag_ttl_active_low, self).read()


class flag_vdac(flag):
	"""
	Boolean pin configured for active high VDAC programmed logic levels.
	"""
	def __init__(self, socket, pin_number, vdac, **kwargs):
		"""
		vdac = voltage to be used for high state.

		kwargs are passed to parent class, e.g., what state to use
		for floating.
		"""
		super(flag_vdac, self).__init__(socket, pin_number, active = PINCON.VDAC, inactive = PINCON.LOGICL, **kwargs)
		if vdac <= 0:
			raise ValueError(vdac)
		self.channel.vdac = volt(vdac)


class flag_vdac_active_low(flag):
	"""
	Boolean pin configured for active low VDAC programmed logic levels.
	"""
	def __init__(self, socket, pin_number, vdac, **kwargs):
		"""
		vdac = voltage to be used for high state.

		kwargs are passed to parent class, e.g., what state to use
		for floating.
		"""
		super(flag_vdac_active_low, self).__init__(socket, pin_number, active = PINCON.LOGICL, inactive = PINCON.VDAC, **kwargs)
		if vdac <= 0:
			raise ValueError(vdac)
		self.channel.vdac = volt(vdac)

	def read(self):
		return not super(flag_vdac_active_low, self).read()


class bus_parallel(object):
	"""
	A collection of pins whose digital states represent an integer
	number.  The pins can be used for output or input.  To set the
	state of the pins, i.e., to use the bus for output, write a value
	to the bus.  To use the bus for input, write None to the bus to
	float the pins.  To read the state of the pins, read a value from
	the bus.

	A bus may be any number of bits in size between 1 and 32,
	inclusively.  Up to 8 buses may be defined and in use
	simultaneously.  For example, a 64 bit bus must be implemented in
	software using 2 of the 8 32 bit buses.  These are limitations of
	the programmer interface firmware.

	default sets the initial state of the bus, which will be passed to
	.write() to perform the configuration.  If not specified, or set to
	None, the bus is initialized to a floating state.  Note that if the
	configured default initial state involves any pins being driven to
	non-zero voltages, those voltages will not take effect until power
	is applied to the socket.  Pins configured for ground potential
	take effect immediately.

	NOTE:  see also devices.bus_proxy_parallel to create a descriptor
	to make calling the .read() and .write() methods of an instance of
	this class more convenient.
	"""
	def __init__(self, programmer, socket, pin_numbers, active, inactive, flt, default = None):
		if not (1 <= len(pin_numbers) <= 32):
			raise ValueError("bus width out of range: 1 <= %d <= 32" % len(pin_numbers))
		self.programmer = programmer
		self.socket = socket
		self.bus_number = self.programmer.get_unused_bus(self)
		self.pin_numbers = tuple(pin_numbers)
		self.max_word = (1 << len(pin_numbers)) - 1
		self.default = default
		# send the bus definition command to the programmer
		command = "B%1XP:%02X%02X%02X%02X" % (self.bus_number, active, inactive, flt, len(pin_numbers))
		command += "".join("%02X" % socket[pin_number].channel for pin_number in pin_numbers)
		self.programmer.write_command(command)
		# set initial state
		for channel in self.channels:
			if PINCON.VDAC not in (active, inactive, flt):
				channel.vdac = 0
			channel.bypass = False
		self.write(self.default)

	@property
	def channels(self):
		"""
		The channel_proxy instances for the pins in this bus, in
		order.
		"""
		return tuple(self.socket[pin_number] for pin_number in self.pin_numbers)

	def read(self):
		"""
		Return the integer value corresponding to the bus' pin
		voltage comparators.  The "high"/"low" states are defined
		by the VTH voltage, not the .inactive and .active states.
		"""
		word, = self.programmer.write_command("B%01XP?" % self.bus_number)
		return word

	def write(self, word):
		"""
		Set the pins of the bus to either .inactive or .active
		according to the bits of the integer word.  If word is None
		the pins are floated.
		"""
		# float the bus if word is None
		if word is None:
			command = "B%01XP-" % self.bus_number
		# otherwise do a range check
		elif not (0 <= word <= self.max_word):
			raise ValueError("0x0 <= word <= 0x%X: 0x%X" % (self.max_word, word))
		# and set the bus equal to word
		elif len(self.pin_numbers) <= 8:
			command = "B%1XP=%02X" % (self.bus_number, word)
		elif len(self.pin_numbers) <= 16:
			command = "B%1XP=%04X" % (self.bus_number, word)
		else:
			command = "B%1XP=%08X" % (self.bus_number, word)
		self.programmer.write_command(command)

	def __len__(self):
		"""
		The number of unique values the bus can represent.
		"""
		return self.max_word + 1

	def __iter__(self):
		"""
		Iterate over the unique values the bus can represent.
		Useful, for example, to iterate over the addresses for a
		ROM chip, or to generate test vectors for a logic chip.
		"""
		return iter(range(len(self)))

	def __del__(self):
		"""
		Tell the USB interface module's firmware to forget this bus
		definition.
		"""
		self.programmer.release_bus(self.bus_number)


class bus_parallel_ttl(bus_parallel):
	"""
	A parallel bus with TTL logic levels.
	"""
	def __init__(self, programmer, socket, pin_numbers, **kwargs):
		super(bus_parallel_ttl, self).__init__(programmer, socket, pin_numbers, active = PINCON.LOGICH, inactive = PINCON.LOGICL, flt = PINCON.DISABLE, **kwargs)


#
# =============================================================================
#
#                        ALLPRO88 Programmer Interface
#
# =============================================================================
#


logger = logging.getLogger(__name__)


class allpro88(object):
	#
	# USB information
	#

	idVendor = 0x1209
	idProduct = 0x000C

	ep_addr_out = 0x02
	ep_addr_in = 0x86

	buf_size = 512	# bytes

	def __init__(self, cal_data = None, idVendor = idVendor, idProduct = idProduct):
		self.buf = usb.core.array.array("B", (0,) * self.buf_size)
		# replace class attributes with instance attributes
		self.idVendor = idVendor
		self.idProduct = idProduct
		# retrieve the USB device
		self.device = usb.core.find(idVendor = self.idVendor, idProduct = self.idProduct)
		if self.device is None:
			raise ValueError("USB device not found (vid:pid = %04X:%04X)" % (self.idVendor, self.idProduct))

		# firmware resets itself and the programmer.  the
		# .__enter__() method repeats much of what this does, but
		# it doesn't hurt to be cautious.
		self.device.set_configuration()

		# initialize channel proxy list.  NOTE:  this step must be
		# completed before initializing the .socket_module
		# attribute.  the socket_module classes use this list to
		# initialize their pin mappings
		self.channels = tuple(channel_proxy(self, i) for i in range(88))

		# retrieve the bit map of installed channel groups and
		# populate the tuple of installed channel drivers
		channel_group_bit_map, = self.write_command("C")
		self.channels_installed = tuple(channel for i, channel in enumerate(self.channels) if (1 << (i // 8)) & channel_group_bit_map)

		# configure for the installed socket module
		try:
			self.socket_module = socket_modules[self.socket_module_id](self)
		except KeyError as e:
			if self.socket_module_id == 0xff:
				logger.warning("no socket module detected")
			else:
				logger.warning("unrecognized socket module ID 0x%02X" % self.socket_module_id)
			self.socket_module = None

		# keep track of what bus numbers are in use
		self.bus = {}

		# install calibration model (defaults if no calibration
		# model is provided).  NOTE:  yes, testing for specific
		# types is bad practice, but this code performs a very
		# narrowly-defined and specific task, and the idea of
		# general-pupose reuse is nonsensical.
		self.cal = {}
		if cal_data is None or isinstance(cal_data, dict):
			# assume a dictionary-valued parameter contains the
			# calibration data.  if no calibration data was
			# provided, we still call .set_calibration() to do
			# the default initialization
			self.set_calibration(cal_data)
		elif isinstance(cal_data, str):
			# assume a string-valued parameter is the name of a
			# file from which to load the calibration data
			with open(cal_data) as f:
				self.set_calibration(yaml.unsafe_load(f))
		else:
			# calling code error
			raise ValueError(cal_data)


	def __enter__(self):
		# ensure the programmer is left in a safe condition (all
		# variable power supplies off, all channel drivers
		# disabled).

		# turn off power supplies
		self.pcr_enable = False

		# ensure all channel drivers are disabled (off), the DAC
		# voltages are 0'ed and the bypass capacitors disabled
		for channel in self.channels:
			channel.config = PINCON.DISABLE
			channel.bypass = False
			channel.vdac = 0
		# set all variable power supplies to 0 V
		self.vpul = 0
		self.load_dacs()	# also updates pin driver DACs
		self.vsr = 0
		self.vth = 0
		self.vtst = 0
		self.itst = 0
		self.vadjth = 0
		self.vadj = 0

		# turn off TTL clock generator
		self.clkgen_mode = CLKGEN_MODE.DISABLE

		# done
		return self


	def __exit__(self, exc_type, exc_val, exc_tb):
		# ensure the programmer is left in a safe condition (all
		# variable power supplies off, all channel drivers
		# disabled).

		# turn off power supplies
		self.pcr_enable = False

		# ensure all channel drivers are disabled (off), the DAC
		# voltages are 0'ed and the bypass capacitors disabled
		for channel in self.channels:
			channel.config = PINCON.DISABLE
			channel.bypass = False
			channel.vdac = 0
		# set all variable power supplies to 0 V
		self.vpul = 0
		self.load_dacs()	# also updates pin driver DACs
		self.vsr = 0
		self.vth = 0
		self.vtst = 0
		self.itst = 0
		self.vadjth = 0
		self.vadj = 0

		# turn off TTL clock generator
		self.clkgen_mode = CLKGEN_MODE.DISABLE

		# done.  if an exception has occured, continue processing
		return False


	def set_calibration(self, cal_data):
		# first, install default calibrations.
		#
		# NOTE:  other code might grab and retain a reference to
		# .cal, therefore do not delete it and create a new object
		# but, instead, clear its contents and re-populate it with
		# the new model.

		self.cal.clear()

		# default programmer DAC curves (actual calibration for my
		# original unit)
		self.cal.update({
			"VADJ":  numpy.polynomial.Polynomial((0.30912373649024794, 0.11765130484398306, 2.970232274042522e-08)),
			"VPUL":  numpy.polynomial.Polynomial((-0.5392560237564137 - 0.18096494173157174, 0.10095824549637102, 2.109251778349706e-08)),
			"VSR":  numpy.polynomial.Polynomial((0.0053290738646065705, 0.09970530978019132, 5.529891853403212e-08)),
			"VTH":  numpy.polynomial.Polynomial((-0.01039799263370611, 0.09980593089448744, 7.15096343691551e-08)),
			"VTST":  numpy.polynomial.Polynomial((0.3012790867808679, 0.10527024428940045, -1.5240068371833107e-05)),
		})

		# now overwrite with calibration model if one has been
		# supplied

		if cal_data is None:
			return

		# programmer DAC curves.  the polynomials model the power
		# supply outputs.  VPUL, however. is placed onto pins
		# through reverse protection diodes, and therefore the
		# actual applied voltage is a little less than the
		# requested voltage by the equivalent of up to several DAC
		# counts.  each pin driver has its own diode, with its own
		# unique forward voltage, but the median forward-bias
		# voltage is recorded in the diode_vf parameter, and by
		# subtracting that from the 0th order term of the
		# polynomial we can correct the model so that it
		# approximates the actual voltage delivered to the pins.
		# VPUL is switched onto a pin by a PNP transistor, and the
		# median of those transistors' emitter-base forward bias
		# voltages is recorded in the trans_vf parameter.  for
		# reasons that require reviewing the circuitry, pull-up
		# voltages less than twice this voltage, or typically
		# around 1.5 V, cannot be applied to the pins because the
		# transistors get turned off.  NOTE:  this limitation is
		# not modeled;  requesting a pull-up voltage less than
		# 2*trans_vf will silently result in the pull-up voltage
		# being, in effect, turned off.

		self.cal["VADJ"] = numpy.polynomial.Polynomial(cal_data["vadj"]["poly"])
		self.cal["VPUL"] = numpy.polynomial.Polynomial(cal_data["vpul"]["poly"])
		self.cal["VPUL"].coef[0] -= cal_data["vpul"]["diode_vf"]
		self.cal["VSR"] = numpy.polynomial.Polynomial(cal_data["vsr"]["poly"])
		self.cal["VTH"] = numpy.polynomial.Polynomial(cal_data["vth"]["poly"])
		self.cal["VTST"] = numpy.polynomial.Polynomial(cal_data["vtst"]["poly"])

		# per channel DAC curves

		for i, channel in enumerate(self.channels):
			try:
				channel_cal_data = cal_data["channel%02d" % i]
			except KeyError:
				# no calibration data for this channel.
				# e.g., this is not a full 88-channel unit.
				# FIXME:  after figuring out how to
				# determine which channels are installed,
				# should add a check here to ensure that
				# all installed channels get calibration
				# data.
				continue
			channel.set_cal(channel_cal_data["vdac"])


	def get_unused_bus(self, bus_obj = None):
		"""
		Returns the integer index of an unused bus definition.
		Raises KeyError if all bus definitions are in use, otherwse
		the bus index that is returned is marked as in-use, and
		bus_obj (default None) is associated with that index in the
		internal bus dictionary.  Calling code may use that to
		associate external objects with the bus.
		"""
		# NOTE:  the range() must match the size of the bus
		# definition array in the firmware source
		unused = set(range(8)) - set(self.bus)
		if not unused:
			raise KeyError("no busses available")
		# pick one
		bus_number = unused.pop()
		# if we've been given something to associate with the bus,
		# put it into the dictionary.  use None, if not, so that
		# the bus is still marked as in use
		self.bus[bus_number] = bus_obj
		return bus_number


	def release_bus(self, bus_number):
		"""
		Mark the given bus index number as unused.  Raises KeyError
		if bus_number is not an index that is currently in use.
		"""
		del self.bus[bus_number]


	def round_v(self, v):
		"""
		Quantize the voltage v to the voltage it will be reported
		as if measured using VTH and the .measure_v() method.
		"""
		return self.vth.cal(self.vth.invcal(v, self), self)


	#
	# USB I/O
	#


	@property
	def serial_number(self):
		"""
		The serial number reported by the USB interface's firmware,
		as a string.  This is not necessarily the historical serial
		number of the programmer hardware, nor is it necessarily a
		"number", or in any specific format, although it is
		expected to be a string that is suitable for use in
		constructing file names and messages for users.  The
		purpose is to provide an ID unique to each programmer so
		calibration files and other hardware-specific data can be
		associated with the correct device, in the event that more
		than one unit is conencted to or available to a given host.
		The value is chosen at firmware compile time, and by
		default it is a UUID, but the developer could choose to set
		it manually to the programmer's original serial number for
		consistency and/or nostalgia, if that number is known (if
		the sticker hasn't been lost).
		"""
		return self.device.serial_number


	def write_command(self, cmd):
		"""
		Write a command to the USB interface, and retrieve, parse
		and return the response.
		"""
		# append a \n to the command, and write the ascii bytes to
		# the USB device.  all commands end in \n.  we append it
		# here to simplify calling code.

		self.device.write(self.ep_addr_out, (cmd + "\n").encode("ascii"))

		# the USB interface's firmware allows a USB packet to
		# contain as many commands as will fit.  it processes them
		# in ordr and places their responses, in order, in the
		# response packet.  I had originally imagined a system in
		# which canned sequences of commands would be assembled and
		# sent to the programmer to quickly perform a sequence of
		# operations without the USB back-and-forth overhead.  the
		# overhead cost of sending the commands one at a time has
		# proven to be insignificant (the programmer's internal bus
		# is quite slow compared to a USB bus), and the convenience
		# of using Python methods to encapsulate I/O operations and
		# provide a high-level interface (which gets in the way of
		# bottling sequences of commands) has been too great to
		# ever make use of the feature.  because the logic needed
		# to split up a response packet proved a bit tricky to get
		# right, I have preserved it, below, even though as written
		# a response packet is now guaranteed to have only a single
		# response in it.

		# every "out" packet generates a response "in" packet.
		# even if we know the commands did not generate responses,
		# we need to retrieve the packet unconditionally or the
		# "in" queue will fill up in the programmer

		n = self.device.read(self.ep_addr_in, self.buf)

		# all commands with responses respond with a single base 16
		# integer.  every response ends in a new line character.
		# some responses are empty, and more than one such response
		# in a row become sequential new line characters.  .split()
		# normally treats sequential new lines as a single
		# whitespace boundary, but if given a specific character to
		# split on (e.g., the new line character) then each new
		# line is its own boundary.  .split() also normally doesn't
		# create an extra split if the string ends in whitespace,
		# but when given a specific character to split on and the
		# string ends in that character then an additional (zero
		# length) split value is created.  since every command ends
		# in a new line, we always get one extra output from
		# .split(), which we must drop from the list

		resps = self.buf[:n].tobytes().decode("ascii").split("\n")[:-1]
		return tuple(int(resp, 16) if resp else None for resp in resps)


	#
	# higher level interface
	#


	def echo(self, val):
		"""
		Echo a 4 digit number (USB loop-back test).
		"""
		assert 0 <= val <= 0xffff
		val, = self.write_command("E%04X" % val)
		return val


	def write_addr(self, addr, val):
		"""
		Write value to register.

		NOTE NOTE NOTE:  physical damage will occur if the wrong
		value is written to the wrong address.  by writing an
		unfortunate value to a pin configuration register, a pin
		might be connected to both a supply voltage and ground
		simultaneously, destroying the pin driver electronics.  for
		testing purposes, writing 0 to any address is safe.  this
		always corresponds to the "disabled" or "turned off"
		setting for any register.  other values should only be
		written after carefully consulting the documentation.
		"""
		assert 0 <= addr <= 0x0fff
		assert 0 <= val <= 0xff
		self.write_command("=%04X%02X" % (addr, val))


	def read_addr(self, addr):
		"""
		Read value from register.
		"""
		assert 0 <= addr <= 0x0fff
		val, = self.write_command("?%04X" % addr)
		assert 0 <= val <= 0xff
		return val


	@property
	def socket_module_id(self):
		"""
		Returns the ID of the socket module installed in the
		programmer, or 0xff is no module is installed.
		"""
		return self.read_addr(0x0280)


	@property
	def system_id(self):
		# in the ALLPRO88 documentation some command line
		# diagnostic tools are shown producing example output
		# reporting a "system ID" of 0x3 and "adapter ID" of 0x11.
		# other examples show an "analog ID" of 0x03.  the "adapter
		# ID" definitely refers to the socket board ID.  mine is
		# 0x11, like the examples (kevtris' is 0x81).  but where do
		# the "system ID" and "analog ID" come from?  are they
		# synonyms for the same number?  kevtris' documentation
		# describes an A1STAT register (status register on the
		# analogue 1 board), whose low nibble he says is hard-wired
		# to report 0x3, curiously the same as both the "system ID"
		# and "analog ID" shown in the examples in the
		# documentation.  my unit also reports 0x3 in that nibble,
		# and the circuit responsible for that behaviour can be
		# seen in the schematics in the serivce manual, where there
		# is a comment written about the value being hard-wired to
		# 0x3.  is this the "system ID" and/or "analog ID"?  are
		# they synonyms?  I'm guessing they are, and it is, and
		# that's what this descriptor returns.
		#
		# Logical Devices made other devices similar to the
		# ALLPRO88, including an older ALLPRO that had only 4
		# channels per pin driver group, not 8, and a single 96 pin
		# DIN connector to the socket module, instead of the two of
		# the ALLPRO88.  it also lacked the ability to generate TTL
		# clock signals, and maybe some other features that I can't
		# remember right now.  socket modules for the older ALLPRO
		# are compatible with the ALLPRO88, they simply mate with
		# the one DIN connector.  the ALLPRO88's other connector
		# (which only carries the higher-numbered channel outputs,
		# and nothing else) is left with nothing plugged into it.
		# my guess is that all ALLPRO-like units look exactly the
		# same to the host PC:  a memory mapped array of registers
		# that control the pin drivers.  they probably used the
		# same ISA interface board for all such systems, and this
		# ID might be how to tell which kind of unit is plugged
		# into the computer, because there might be literally no
		# other way to tell the difference.  if those guesses are
		# correct, then this library and the USB interface board
		# will work just fine with an ALLPRO (non-88), perhaps with
		# just a few features disabled.  in that case, this library
		# should use this system ID code to enable or disable the
		# appropriate features.  someone with an ALLPRO (non-88)
		# would need to do some research on that.

		return self.read_addr(0x0300) & 0xf


	pcr_enable = property(fset = lambda self, enable: self.write_addr(0x030c, PCR.ENABLE | PCR.NIDLE if enable else PCR.DISABLE))


	@property
	def clkgen_mode(self):
		raise NotImplementedError("write-only address")

	@clkgen_mode.setter
	def clkgen_mode(self, val):
		if val & 0x07 == 0x07:
			raise ValueError("mode 0x07 forbidden")
		self.write_addr(0x038B, val)


	vsr = dacregister(address = 0x0300, cal_key = "VSR")
	vth = dacregister(address = 0x0301, cal_key = "VTH")
	vadj = dacregister(address = 0x0302, transient = 0.05, cal_key = "VADJ")
	vadjth = dacregister(address = 0x0303)
	# must call .load_dacs() for vpul changes
	vpul = dacregister(address = 0x0305, cal_key = "VPUL")
	vtst = dacregister(address = 0x0386, cal_key = "VTST")
	itst = dacregister(address = 0x0387)


	def load_dacs(self, transient = 0.001):
		self.write_addr(0x0308, 0)
		# wait for transient response
		time.sleep(transient)


	def measure_vadj_load(self):
		"""
		Use bisection search with VADJTH to measure the adjustable
		power supply's current sense voltage, and report it as a
		fraction of the power supply's maximum output current.
		"""
		vdac, = self.write_command("V")

		# VADJTH is generated by U3 on analogue control 1, an
		# AD7226.  this chip's voltage output is Vref * (DAC value)
		# / 256 (note:  max voltage is 1 LSB less than Vref).  Vref
		# for the chip is generated by an LM317 with an adjustment
		# crazy-glued in place.  this is an important calibration
		# point in the circuit.  in mine, the Vref is +5.06 V, but
		# I believe it's meant to be 5.1 V.  since mine is out by
		# less than 1% I'm going to call that OK.

		# convert numeric DAC value to DAC output voltage
		vdac *= 5.1 / 256.

		# this value has been selected by comparing it to the
		# output of the VADJ power supply's current sense
		# amplifier.  my schematic is too blurry to figure out what
		# the sense resistor value is, so I don't know how to
		# convert voltage to current, but when the amplifier's
		# output crosses +5 V that triggers the over-current
		# shut-down circuit in the VADJ power supply, so we know
		# the allowed values are in the range [0 V, 5 V].  rather
		# than convert to a calibrated current in amperes, I return
		# a number indicating the current as a fraction of maximum.
		# nominally that means the range [0, 1.0] but if the
		# circuit fails to prevent an overload it could be seen to
		# be above that.
		return vdac / 5.0


def command_line_banner(programmer):
	"""
	Text banner displayed by command-line tools.
	"""
	# FIXME:  use logger?  and do this in allpro88.__init__()?
	print("serial number:  %s\nsystem ID:  0x%X\nsocket module:  %s\nchannels installed (%d):  %s" % (programmer.serial_number, programmer.system_id, programmer.socket_module.name if programmer.socket_module else "not detected", len(programmer.channels_installed), tuple(channel.channel for channel in programmer.channels_installed)))
